version: '3.8'
services:

    reverse-proxy:
        image: traefik:v2.6
        command: --api.insecure=true --providers.docker --metrics.datadog=true --metrics.datadog.address=127.0.0.1:8125
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    database:
        hostname: database
        platform: linux/x86_64
        image: mariadb:10.3
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: cards
            MYSQL_DATABASE: cards
            MYSQL_USER: cards
            MYSQL_PASSWORD: cards
        ports:
            - "3306:3306"
        labels:
            - "traefik.enable=false"

    server:
        build:
            context: .
        depends_on:
            - database
        volumes:
            - ./:/var/www/html/
        labels:
            - "traefik.http.routers.wp.rule=Host(`cards.local`)"
